export default {
  navMenu: {
    welcome: 'Добро пожаловать',
    signIn: 'Войти',
    signUp: 'Зарегистрироваться',
    logout: 'Выйти',
    openMenu: 'Открыть меню',
    closeMenu: 'Закрыть меню',
  },
  authForm: {
    signInTitle: 'Вход',
    signUpTitle: 'Регистрация',
    emailLabel: 'Электронная почта',
    passwordLabel: 'Пароль',
    nameLabel: 'Имя',
    confirmPasswordLabel: 'Подтвердите пароль',
    passwordStrength: 'Сложность пароля',
    btnText: 'Отправить',
    showPassword: 'Показать пароль',
    hidePassword: 'Спрятать пароль',
    noNaveAccount: 'Еще нет аккаунта?',
    haveAccount: 'Уже есть аккаунт?',
    errors: {
      name: 'Первая буква должна быть заглавной',
      email: 'Неверный формат. Пожалуйста, введите корректный адрес электронной почты, например, john@smith.com.',

      passwordUpper: 'Пароль должен содержать хотя бы одну заглавную букву [A-Z]',
      passwordLower: 'Пароль должен содержать хотя бы одну строчную букву [a-z]',
      passwordNumeric: 'Пароль должен содержать хотя бы одну цифру [0-9]',
      passwordCharacter: 'Пароль должен содержать хотя бы один специальный символ: ~`!@#$%^&*()-_+={}[]|\\;:"<>,./?',
      passwordLength: 'Пароль должен быть не менее 8 символов',

      confirmPassword: 'Пароли не совпадают',
      required: 'Обязательное поле',
    },
  },

  errorPage: {
    title: 'Ошибка',
    text: 'Что-то пошло не так',
    btnText: 'На главную',
  },
  notFoundPage: {
    text: 'Страница не найдена',
    btnText: 'На главную',
  },
  welcomePage: {
    welcomeTitle:
      'GraphiQL — это интегрированная среда разработки (IDE) GraphQL. Это мощный (и потрясающий во всех отношениях) инструмент, который вы часто будете использовать при создании веб-сайтов. Он предлагает подсветку синтаксиса, автозаполнение, автоматическое документирование и многое другое.',
    toEditor: 'Перейти в редактор',
    developers: 'Разработчики',
    sponsored: 'При поддержке',
    rssAbout:
      'RS School — это бесплатная образовательная программа, проводимая сообществом разработчиков The Rolling Scopes с 2013 года.',
    alexey: 'Алексей Пащук',
    volha: 'Ольга Матринчик',
  },
  graphiQLPage: {
    docs: 'Документация',
    docsInstruction: 'Схема GraphQL предоставляет корневой тип для каждого типа операции.',
    docsNotFound: 'Документация не найдена',
    editor: 'Редактор',
    response: 'Ответ',
    queryEnter: 'Введите ваш запрос',
    endpointEnter: 'Введите API запроса',
    endpointSubmit: 'Подтвердите API запроса',
    back: '\u2190 Назад',
    rootType: 'Основные Типы',
    schemaTypes: 'Все Типы Схемы',
    docsShow: 'Показать документацию',
    docsHide: 'Скрыть документацию',
    runQuery: 'Выполнить запрос',
    toolsShow: 'Показать инструменты',
    toolsHide: 'Скрыть инструменты',
    prettify: 'Форматировать',
  },
};
